# modules/dialog_database.py

GOTHIC_NPC_DATABASE = {
    "high_temple_guard": {
        "brazilian": "High Temple Guard",
        "english": "High Temple Guard",
        "french": "High Temple Guard",
        "german": "High Temple Guard",
        "italian": "High Temple Guard",
        "japanese": "High Temple Guard",
        "polish": "High Temple Guard",
        "russian": "Элитный храмовый страж",
        "schinese": "High Temple Guard",
        "spanish": "High Temple Guard"
    },
    "arlin": {
        "brazilian": "Arlin",
        "english": "Arlin",
        "french": "Arlin",
        "german": "Arlin",
        "italian": "Arlin",
        "japanese": "Arlin",
        "polish": "Arlin",
        "russian": "Арлин",
        "schinese": "Arlin",
        "spanish": "Arlin"
    },
    "brannok": {
        "brazilian": "Brannok",
        "english": "Brannok",
        "french": "Brannok",
        "german": "Brannok",
        "italian": "Brannok",
        "japanese": "Brannok",
        "polish": "Brannok",
        "russian": "Браннок",
        "schinese": "Brannok",
        "spanish": "Brannok"
    },
    "outlaw": {
        "brazilian": "Outlaw",
        "english": "Outlaw",
        "french": "Outlaw",
        "german": "Outlaw",
        "italian": "Outlaw",
        "japanese": "Outlaw",
        "polish": "Outlaw",
        "russian": "Бандит",
        "schinese": "Outlaw",
        "spanish": "Outlaw"
    },
    "quentin": {
        "brazilian": "Quentin",
        "english": "Quentin",
        "french": "Quentin",
        "german": "Quentin",
        "italian": "Quentin",
        "japanese": "Quentin",
        "polish": "Quentin",
        "russian": "Квентин",
        "schinese": "Quentin",
        "spanish": "Quentin"
    },
    "torik": {
        "brazilian": "Torik",
        "english": "Torik",
        "french": "Torik",
        "german": "Torik",
        "italian": "Torik",
        "japanese": "Torik",
        "polish": "Torik",
        "russian": "Торик",
        "schinese": "Torik",
        "spanish": "Torik"
    },
    "guard": {
        "brazilian": "Guard",
        "english": "Guard",
        "french": "Guard",
        "german": "Guard",
        "italian": "Guard",
        "japanese": "Guard",
        "polish": "Guard",
        "russian": "Стражник",
        "schinese": "Guard",
        "spanish": "Guard"
    },
    "mage": {
        "brazilian": "Mage",
        "english": "Mage",
        "french": "Mage",
        "german": "Mage",
        "italian": "Mage",
        "japanese": "Mage",
        "polish": "Mage",
        "russian": "Маг",
        "schinese": "Mage",
        "spanish": "Mage"
    },
    "judge": {
        "brazilian": "Judge",
        "english": "Judge",
        "french": "Judge",
        "german": "Judge",
        "italian": "Judge",
        "japanese": "Judge",
        "polish": "Judge",
        "russian": "Судья",
        "schinese": "Judge",
        "spanish": "Judge"
    },
    "kingadvisor": {
        "brazilian": "Kingadvisor",
        "english": "Kingadvisor",
        "french": "Kingadvisor",
        "german": "Kingadvisor",
        "italian": "Kingadvisor",
        "japanese": "Kingadvisor",
        "polish": "Kingadvisor",
        "russian": "Советник Короля",
        "schinese": "Kingadvisor",
        "spanish": "Kingadvisor"
    },
    "kingrhobar": {
        "brazilian": "Kingrhobar",
        "english": "Kingrhobar",
        "french": "Kingrhobar",
        "german": "Kingrhobar",
        "italian": "Kingrhobar",
        "japanese": "Kingrhobar",
        "polish": "Kingrhobar",
        "russian": "Король Робар",
        "schinese": "Kingrhobar",
        "spanish": "Kingrhobar"
    },
    "narrator": {
        "brazilian": "Narrator",
        "english": "Narrator",
        "french": "Narrator",
        "german": "Narrator",
        "italian": "Narrator",
        "japanese": "Narrator",
        "polish": "Narrator",
        "russian": "Рассказчик",
        "schinese": "Narrator",
        "spanish": "Narrator"
    },
    "gomez": {
        "brazilian": "Gomez",
        "english": "Gomez",
        "french": "Gomez",
        "german": "Gomez",
        "italian": "Gomez",
        "japanese": "Gomez",
        "polish": "Gomez",
        "russian": "Гомез",
        "schinese": "Gomez",
        "spanish": "Gomez"
    },
    "mad_diego": {
        "brazilian": "Mad Diego",
        "english": "Mad Diego",
        "french": "Mad Diego",
        "german": "Mad Diego",
        "italian": "Mad Diego",
        "japanese": "Mad Diego",
        "polish": "Mad Diego",
        "russian": "Безумный Диего",
        "schinese": "Mad Diego",
        "spanish": "Mad Diego"
    },
    "bullit": {
        "brazilian": "Bullit",
        "english": "Bullit",
        "french": "Bullit",
        "german": "Bullit",
        "italian": "Bullit",
        "japanese": "Bullit",
        "polish": "Bullit",
        "russian": "Буллит",
        "schinese": "Bullit",
        "spanish": "Bullit"
    },
    "stone": {
        "brazilian": "Stone",
        "english": "Stone",
        "french": "Stone",
        "german": "Stone",
        "italian": "Stone",
        "japanese": "Stone",
        "polish": "Stone",
        "russian": "Стоун",
        "schinese": "Stone",
        "spanish": "Stone"
    },
    "xardas": {
        "brazilian": "Xardas",
        "english": "Xardas",
        "french": "Xardas",
        "german": "Xardas",
        "italian": "Xardas",
        "japanese": "Xardas",
        "polish": "Xardas",
        "russian": "Ксардас",
        "schinese": "Xardas",
        "spanish": "Xardas"
    },
    "greatprayer": {
        "brazilian": "Greatprayer",
        "english": "Greatprayer",
        "french": "Greatprayer",
        "german": "Greatprayer",
        "italian": "Greatprayer",
        "japanese": "Greatprayer",
        "polish": "Greatprayer",
        "russian": "Церемония призыва",
        "schinese": "Greatprayer",
        "spanish": "Greatprayer"
    },
    "baal_lukor": {
        "brazilian": "Baal Lukor",
        "english": "Baal Lukor",
        "french": "Baal Lukor",
        "german": "Baal Lukor",
        "italian": "Baal Lukor",
        "japanese": "Baal Lukor",
        "polish": "Baal Lukor",
        "russian": "Идол Люкор",
        "schinese": "Baal Lukor",
        "spanish": "Baal Lukor"
    },
    "cor_angar": {
        "brazilian": "Cor Angar",
        "english": "Cor Angar",
        "french": "Cor Angar",
        "german": "Cor Angar",
        "italian": "Cor Angar",
        "japanese": "Cor Angar",
        "polish": "Cor Angar",
        "russian": "Кор Ангар",
        "schinese": "Cor Angar",
        "spanish": "Cor Angar"
    },
    "cor_kalom": {
        "brazilian": "Cor Kalom",
        "english": "Cor Kalom",
        "french": "Cor Kalom",
        "german": "Cor Kalom",
        "italian": "Cor Kalom",
        "japanese": "Cor Kalom",
        "polish": "Cor Kalom",
        "russian": "Кор Галом",
        "schinese": "Cor Kalom",
        "spanish": "Cor Kalom"
    },
    "y_berion": {
        "brazilian": "Y'Berion",
        "english": "Y'Berion",
        "french": "Y'Berion",
        "german": "Y'Berion",
        "italian": "Y'Berion",
        "japanese": "Y'Berion",
        "polish": "Y'Berion",
        "russian": "Ю’Берион",
        "schinese": "Y'Berion",
        "spanish": "Y'Berion"
    },
    "mad_lester": {
        "brazilian": "Mad Lester",
        "english": "Mad Lester",
        "french": "Mad Lester",
        "german": "Mad Lester",
        "italian": "Mad Lester",
        "japanese": "Mad Lester",
        "polish": "Mad Lester",
        "russian": "Безумный Лестер",
        "schinese": "Mad Lester",
        "spanish": "Mad Lester"
    },
    "joru": {
        "brazilian": "Joru",
        "english": "Joru",
        "french": "Joru",
        "german": "Joru",
        "italian": "Joru",
        "japanese": "Joru",
        "polish": "Joru",
        "russian": "Йору",
        "schinese": "Joru",
        "spanish": "Joru"
    },
    "firemages": {
        "brazilian": "Firemages",
        "english": "Firemages",
        "french": "Firemages",
        "german": "Firemages",
        "italian": "Firemages",
        "japanese": "Firemages",
        "polish": "Firemages",
        "russian": "Firemages",
        "schinese": "Firemages",
        "spanish": "Firemages"
    },
    "corristo": {
        "brazilian": "Corristo",
        "english": "Corristo",
        "french": "Corristo",
        "german": "Corristo",
        "italian": "Corristo",
        "japanese": "Corristo",
        "polish": "Corristo",
        "russian": "Корристо",
        "schinese": "Corristo",
        "spanish": "Corristo"
    },
    "milten": {
        "brazilian": "Milten",
        "english": "Milten",
        "french": "Milten",
        "german": "Milten",
        "italian": "Milten",
        "japanese": "Milten",
        "polish": "Milten",
        "russian": "Мильтен",
        "schinese": "Milten",
        "spanish": "Milten"
    },
    "uriziel": {
        "brazilian": "Uriziel",
        "english": "Uriziel",
        "french": "Uriziel",
        "german": "Uriziel",
        "italian": "Uriziel",
        "japanese": "Uriziel",
        "polish": "Uriziel",
        "russian": "Уризель",
        "schinese": "Uriziel",
        "spanish": "Uriziel"
    },
    "nefarius": {
        "brazilian": "Nefarius",
        "english": "Nefarius",
        "french": "Nefarius",
        "german": "Nefarius",
        "italian": "Nefarius",
        "japanese": "Nefarius",
        "polish": "Nefarius",
        "russian": "Нефариус",
        "schinese": "Nefarius",
        "spanish": "Nefarius"
    },
    "killian": {
        "brazilian": "Killian",
        "english": "Killian",
        "french": "Killian",
        "german": "Killian",
        "italian": "Killian",
        "japanese": "Killian",
        "polish": "Killian",
        "russian": "Килиан",
        "schinese": "Killian",
        "spanish": "Killian"
    },
    "extro": {
        "brazilian": "Extro",
        "english": "Extro",
        "french": "Extro",
        "german": "Extro",
        "italian": "Extro",
        "japanese": "Extro",
        "polish": "Extro",
        "russian": "Эпилог",
        "schinese": "Extro",
        "spanish": "Extro"
    },
    "tarrok": {
        "brazilian": "Tarrok",
        "english": "Tarrok",
        "french": "Tarrok",
        "german": "Tarrok",
        "italian": "Tarrok",
        "japanese": "Tarrok",
        "polish": "Tarrok",
        "russian": "Таррок",
        "schinese": "Tarrok",
        "spanish": "Tarrok"
    },
    "senyan": {
        "brazilian": "Senyan",
        "english": "Senyan",
        "french": "Senyan",
        "german": "Senyan",
        "italian": "Senyan",
        "japanese": "Senyan",
        "polish": "Senyan",
        "russian": "Сеньян",
        "schinese": "Senyan",
        "spanish": "Senyan"
    },
    "swiney": {
        "brazilian": "Swiney",
        "english": "Swiney",
        "french": "Swiney",
        "german": "Swiney",
        "italian": "Swiney",
        "japanese": "Swiney",
        "polish": "Swiney",
        "russian": "Суини",
        "schinese": "Swiney",
        "spanish": "Swiney"
    },
    "baloro": {
        "brazilian": "Baloro",
        "english": "Baloro",
        "french": "Baloro",
        "german": "Baloro",
        "italian": "Baloro",
        "japanese": "Baloro",
        "polish": "Baloro",
        "russian": "Балоро",
        "schinese": "Baloro",
        "spanish": "Baloro"
    },
    "okyl": {
        "brazilian": "Okyl",
        "english": "Okyl",
        "french": "Okyl",
        "german": "Okyl",
        "italian": "Okyl",
        "japanese": "Okyl",
        "polish": "Okyl",
        "russian": "Окил",
        "schinese": "Okyl",
        "spanish": "Okyl"
    },
    "generic_aboutcamp_sc_tpl": {
        "brazilian": "Generic_aboutcamp_sc_tpl",
        "english": "Generic_aboutcamp_sc_tpl",
        "french": "Generic_aboutcamp_sc_tpl",
        "german": "Generic_aboutcamp_sc_tpl",
        "italian": "Generic_aboutcamp_sc_tpl",
        "japanese": "Generic_aboutcamp_sc_tpl",
        "polish": "Generic_aboutcamp_sc_tpl",
        "russian": "Generic_aboutcamp_sc_tpl",
        "schinese": "Generic_aboutcamp_sc_tpl",
        "spanish": "Generic_aboutcamp_sc_tpl"
    },
    "finalboss": {
        "brazilian": "Finalboss",
        "english": "Finalboss",
        "french": "Finalboss",
        "german": "Finalboss",
        "italian": "Finalboss",
        "japanese": "Finalboss",
        "polish": "Finalboss",
        "russian": "Финальный босс",
        "schinese": "Finalboss",
        "spanish": "Finalboss"
    },
    "generic_aboutcamp_fm_org": {
        "brazilian": "Generic_aboutcamp_fm_org",
        "english": "Generic_aboutcamp_fm_org",
        "french": "Generic_aboutcamp_fm_org",
        "german": "Generic_aboutcamp_fm_org",
        "italian": "Generic_aboutcamp_fm_org",
        "japanese": "Generic_aboutcamp_fm_org",
        "polish": "Generic_aboutcamp_fm_org",
        "russian": "Generic_aboutcamp_fm_org",
        "schinese": "Generic_aboutcamp_fm_org",
        "spanish": "Generic_aboutcamp_fm_org"
    },
    "generic_aboutcamp_fm_sfb": {
        "brazilian": "Generic_aboutcamp_fm_sfb",
        "english": "Generic_aboutcamp_fm_sfb",
        "french": "Generic_aboutcamp_fm_sfb",
        "german": "Generic_aboutcamp_fm_sfb",
        "italian": "Generic_aboutcamp_fm_sfb",
        "japanese": "Generic_aboutcamp_fm_sfb",
        "polish": "Generic_aboutcamp_fm_sfb",
        "russian": "Generic_aboutcamp_fm_sfb",
        "schinese": "Generic_aboutcamp_fm_sfb",
        "spanish": "Generic_aboutcamp_fm_sfb"
    },
    "generic_aboutcamp_fm_sld": {
        "brazilian": "Generic_aboutcamp_fm_sld",
        "english": "Generic_aboutcamp_fm_sld",
        "french": "Generic_aboutcamp_fm_sld",
        "german": "Generic_aboutcamp_fm_sld",
        "italian": "Generic_aboutcamp_fm_sld",
        "japanese": "Generic_aboutcamp_fm_sld",
        "polish": "Generic_aboutcamp_fm_sld",
        "russian": "Generic_aboutcamp_fm_sld",
        "schinese": "Generic_aboutcamp_fm_sld",
        "spanish": "Generic_aboutcamp_fm_sld"
    },
    "jan": {
        "brazilian": "Jan",
        "english": "Jan",
        "french": "Jan",
        "german": "Jan",
        "italian": "Jan",
        "japanese": "Jan",
        "polish": "Jan",
        "russian": "Джан",
        "schinese": "Jan",
        "spanish": "Jan"
    },
    "generic_aboutcamp_nc_bau": {
        "brazilian": "Generic_aboutcamp_nc_bau",
        "english": "Generic_aboutcamp_nc_bau",
        "french": "Generic_aboutcamp_nc_bau",
        "german": "Generic_aboutcamp_nc_bau",
        "italian": "Generic_aboutcamp_nc_bau",
        "japanese": "Generic_aboutcamp_nc_bau",
        "polish": "Generic_aboutcamp_nc_bau",
        "russian": "Generic_aboutcamp_nc_bau",
        "schinese": "Generic_aboutcamp_nc_bau",
        "spanish": "Generic_aboutcamp_nc_bau"
    },
    "generic_aboutcamp_nc_org": {
        "brazilian": "Generic_aboutcamp_nc_org",
        "english": "Generic_aboutcamp_nc_org",
        "french": "Generic_aboutcamp_nc_org",
        "german": "Generic_aboutcamp_nc_org",
        "italian": "Generic_aboutcamp_nc_org",
        "japanese": "Generic_aboutcamp_nc_org",
        "polish": "Generic_aboutcamp_nc_org",
        "russian": "Generic_aboutcamp_nc_org",
        "schinese": "Generic_aboutcamp_nc_org",
        "spanish": "Generic_aboutcamp_nc_org"
    },
    "generic_aboutcamp_nc_sld": {
        "brazilian": "Generic_aboutcamp_nc_sld",
        "english": "Generic_aboutcamp_nc_sld",
        "french": "Generic_aboutcamp_nc_sld",
        "german": "Generic_aboutcamp_nc_sld",
        "italian": "Generic_aboutcamp_nc_sld",
        "japanese": "Generic_aboutcamp_nc_sld",
        "polish": "Generic_aboutcamp_nc_sld",
        "russian": "Generic_aboutcamp_nc_sld",
        "schinese": "Generic_aboutcamp_nc_sld",
        "spanish": "Generic_aboutcamp_nc_sld"
    },
    "generic_aboutcamp_oc_grd": {
        "brazilian": "Generic_aboutcamp_oc_grd",
        "english": "Generic_aboutcamp_oc_grd",
        "french": "Generic_aboutcamp_oc_grd",
        "german": "Generic_aboutcamp_oc_grd",
        "italian": "Generic_aboutcamp_oc_grd",
        "japanese": "Generic_aboutcamp_oc_grd",
        "polish": "Generic_aboutcamp_oc_grd",
        "russian": "Generic_aboutcamp_oc_grd",
        "schinese": "Generic_aboutcamp_oc_grd",
        "spanish": "Generic_aboutcamp_oc_grd"
    },
    "generic_aboutcamp_oc_stt": {
        "brazilian": "Generic_aboutcamp_oc_stt",
        "english": "Generic_aboutcamp_oc_stt",
        "french": "Generic_aboutcamp_oc_stt",
        "german": "Generic_aboutcamp_oc_stt",
        "italian": "Generic_aboutcamp_oc_stt",
        "japanese": "Generic_aboutcamp_oc_stt",
        "polish": "Generic_aboutcamp_oc_stt",
        "russian": "Generic_aboutcamp_oc_stt",
        "schinese": "Generic_aboutcamp_oc_stt",
        "spanish": "Generic_aboutcamp_oc_stt"
    },
    "generic_aboutcamp_oc_vlk": {
        "brazilian": "Generic_aboutcamp_oc_vlk",
        "english": "Generic_aboutcamp_oc_vlk",
        "french": "Generic_aboutcamp_oc_vlk",
        "german": "Generic_aboutcamp_oc_vlk",
        "italian": "Generic_aboutcamp_oc_vlk",
        "japanese": "Generic_aboutcamp_oc_vlk",
        "polish": "Generic_aboutcamp_oc_vlk",
        "russian": "Generic_aboutcamp_oc_vlk",
        "schinese": "Generic_aboutcamp_oc_vlk",
        "spanish": "Generic_aboutcamp_oc_vlk"
    },
    "generic_aboutcamp_om_grd": {
        "brazilian": "Generic_aboutcamp_om_grd",
        "english": "Generic_aboutcamp_om_grd",
        "french": "Generic_aboutcamp_om_grd",
        "german": "Generic_aboutcamp_om_grd",
        "italian": "Generic_aboutcamp_om_grd",
        "japanese": "Generic_aboutcamp_om_grd",
        "polish": "Generic_aboutcamp_om_grd",
        "russian": "Generic_aboutcamp_om_grd",
        "schinese": "Generic_aboutcamp_om_grd",
        "spanish": "Generic_aboutcamp_om_grd"
    },
    "generic_aboutcamp_om_vlk": {
        "brazilian": "Generic_aboutcamp_om_vlk",
        "english": "Generic_aboutcamp_om_vlk",
        "french": "Generic_aboutcamp_om_vlk",
        "german": "Generic_aboutcamp_om_vlk",
        "italian": "Generic_aboutcamp_om_vlk",
        "japanese": "Generic_aboutcamp_om_vlk",
        "polish": "Generic_aboutcamp_om_vlk",
        "russian": "Generic_aboutcamp_om_vlk",
        "schinese": "Generic_aboutcamp_om_vlk",
        "spanish": "Generic_aboutcamp_om_vlk"
    },
    "mad_orc": {
        "brazilian": "Mad Orc",
        "english": "Mad Orc",
        "french": "Mad Orc",
        "german": "Mad Orc",
        "italian": "Mad Orc",
        "japanese": "Mad Orc",
        "polish": "Mad Orc",
        "russian": "Безумный орк",
        "schinese": "Mad Orc",
        "spanish": "Mad Orc"
    },
    "muk": {
        "brazilian": "Muk",
        "english": "Muk",
        "french": "Muk",
        "german": "Muk",
        "italian": "Muk",
        "japanese": "Muk",
        "polish": "Muk",
        "russian": "Мук",
        "schinese": "Muk",
        "spanish": "Muk"
    },
    "umakhal": {
        "brazilian": "Umakhal",
        "english": "Umakhal",
        "french": "Umakhal",
        "german": "Umakhal",
        "italian": "Umakhal",
        "japanese": "Umakhal",
        "polish": "Umakhal",
        "russian": "Умакхал",
        "schinese": "Umakhal",
        "spanish": "Umakhal"
    },
    "grazkrak": {
        "brazilian": "Grazkrak",
        "english": "Grazkrak",
        "french": "Grazkrak",
        "german": "Grazkrak",
        "italian": "Grazkrak",
        "japanese": "Grazkrak",
        "polish": "Grazkrak",
        "russian": "Гразкрак",
        "schinese": "Grazkrak",
        "spanish": "Grazkrak"
    },
    "to_churnagg": {
        "brazilian": "To-Churnagg",
        "english": "To-Churnagg",
        "french": "To-Churnagg",
        "german": "To-Churnagg",
        "italian": "To-Churnagg",
        "japanese": "To-Churnagg",
        "polish": "To-Churnagg",
        "russian": "То-Чурнаг",
        "schinese": "To-Churnagg",
        "spanish": "To-Churnagg"
    },
    "generic_aboutcamp_sc_nov": {
        "brazilian": "Generic_aboutcamp_sc_nov",
        "english": "Generic_aboutcamp_sc_nov",
        "french": "Generic_aboutcamp_sc_nov",
        "german": "Generic_aboutcamp_sc_nov",
        "italian": "Generic_aboutcamp_sc_nov",
        "japanese": "Generic_aboutcamp_sc_nov",
        "polish": "Generic_aboutcamp_sc_nov",
        "russian": "Generic_aboutcamp_sc_nov",
        "schinese": "Generic_aboutcamp_sc_nov",
        "spanish": "Generic_aboutcamp_sc_nov"
    },
    "findnpc": {
        "brazilian": "Findnpc",
        "english": "Findnpc",
        "french": "Findnpc",
        "german": "Findnpc",
        "italian": "Findnpc",
        "japanese": "Findnpc",
        "polish": "Findnpc",
        "russian": "Поиск NPC",
        "schinese": "Findnpc",
        "spanish": "Findnpc"
    },
    "dreamedland": {
        "brazilian": "Dreamedland",
        "english": "Dreamedland",
        "french": "Dreamedland",
        "german": "Dreamedland",
        "italian": "Dreamedland",
        "japanese": "Dreamedland",
        "polish": "Dreamedland",
        "russian": "Земля грёз",
        "schinese": "Dreamedland",
        "spanish": "Dreamedland"
    },
    "rankupguard": {
        "brazilian": "Rankupguard",
        "english": "Rankupguard",
        "french": "Rankupguard",
        "german": "Rankupguard",
        "italian": "Rankupguard",
        "japanese": "Rankupguard",
        "polish": "Rankupguard",
        "russian": "Rankupguard",
        "schinese": "Rankupguard",
        "spanish": "Rankupguard"
    },
    "payfine": {
        "brazilian": "Payfine",
        "english": "Payfine",
        "french": "Payfine",
        "german": "Payfine",
        "italian": "Payfine",
        "japanese": "Payfine",
        "polish": "Payfine",
        "russian": "Уплата штрафа",
        "schinese": "Payfine",
        "spanish": "Payfine"
    },
    "nyras": {
        "brazilian": "Nyras",
        "english": "Nyras",
        "french": "Nyras",
        "german": "Nyras",
        "italian": "Nyras",
        "japanese": "Nyras",
        "polish": "Nyras",
        "russian": "Нирас",
        "schinese": "Nyras",
        "spanish": "Nyras"
    },
    "scene": {
        "brazilian": "Scene",
        "english": "Scene",
        "french": "Scene",
        "german": "Scene",
        "italian": "Scene",
        "japanese": "Scene",
        "polish": "Scene",
        "russian": "Интро",
        "schinese": "Scene",
        "spanish": "Scene"
    },
    "dam_lurker": {
        "brazilian": "Dam Lurker",
        "english": "Dam Lurker",
        "french": "Dam Lurker",
        "german": "Dam Lurker",
        "italian": "Dam Lurker",
        "japanese": "Dam Lurker",
        "polish": "Dam Lurker",
        "russian": "Шныг с плотины",
        "schinese": "Dam Lurker",
        "spanish": "Dam Lurker"
    },
    "horatio": {
        "brazilian": "Horatio",
        "english": "Horatio",
        "french": "Horatio",
        "german": "Horatio",
        "italian": "Horatio",
        "japanese": "Horatio",
        "polish": "Horatio",
        "russian": "Горацио",
        "schinese": "Horatio",
        "spanish": "Horatio"
    },
    "jeremiah": {
        "brazilian": "Jeremiah",
        "english": "Jeremiah",
        "french": "Jeremiah",
        "german": "Jeremiah",
        "italian": "Jeremiah",
        "japanese": "Jeremiah",
        "polish": "Jeremiah",
        "russian": "Иеремия",
        "schinese": "Jeremiah",
        "spanish": "Jeremiah"
    },
    "malon": {
        "brazilian": "Malon",
        "english": "Malon",
        "french": "Malon",
        "german": "Malon",
        "italian": "Malon",
        "japanese": "Malon",
        "polish": "Malon",
        "russian": "Малон",
        "schinese": "Malon",
        "spanish": "Malon"
    },
    "pock": {
        "brazilian": "Pock",
        "english": "Pock",
        "french": "Pock",
        "german": "Pock",
        "italian": "Pock",
        "japanese": "Pock",
        "polish": "Pock",
        "russian": "Пок",
        "schinese": "Pock",
        "spanish": "Pock"
    },
    "rayk": {
        "brazilian": "Rayk",
        "english": "Rayk",
        "french": "Rayk",
        "german": "Rayk",
        "italian": "Rayk",
        "japanese": "Rayk",
        "polish": "Rayk",
        "russian": "Райк",
        "schinese": "Rayk",
        "spanish": "Rayk"
    },
    "rice_lord": {
        "brazilian": "Rice Lord",
        "english": "Rice Lord",
        "french": "Rice Lord",
        "german": "Rice Lord",
        "italian": "Rice Lord",
        "japanese": "Rice Lord",
        "polish": "Rice Lord",
        "russian": "Рисовый Лорд",
        "schinese": "Rice Lord",
        "spanish": "Rice Lord"
    },
    "rufus": {
        "brazilian": "Rufus",
        "english": "Rufus",
        "french": "Rufus",
        "german": "Rufus",
        "italian": "Rufus",
        "japanese": "Rufus",
        "polish": "Rufus",
        "russian": "Руфус",
        "schinese": "Rufus",
        "spanish": "Rufus"
    },
    "cronos": {
        "brazilian": "Cronos",
        "english": "Cronos",
        "french": "Cronos",
        "german": "Cronos",
        "italian": "Cronos",
        "japanese": "Cronos",
        "polish": "Cronos",
        "russian": "Кронос",
        "schinese": "Cronos",
        "spanish": "Cronos"
    },
    "merdarion": {
        "brazilian": "Merdarion",
        "english": "Merdarion",
        "french": "Merdarion",
        "german": "Merdarion",
        "italian": "Merdarion",
        "japanese": "Merdarion",
        "polish": "Merdarion",
        "russian": "Мердарион",
        "schinese": "Merdarion",
        "spanish": "Merdarion"
    },
    "myxir": {
        "brazilian": "Myxir",
        "english": "Myxir",
        "french": "Myxir",
        "german": "Myxir",
        "italian": "Myxir",
        "japanese": "Myxir",
        "polish": "Myxir",
        "russian": "Миксир",
        "schinese": "Myxir",
        "spanish": "Myxir"
    },
    "riordian": {
        "brazilian": "Riordian",
        "english": "Riordian",
        "french": "Riordian",
        "german": "Riordian",
        "italian": "Riordian",
        "japanese": "Riordian",
        "polish": "Riordian",
        "russian": "Риордиан",
        "schinese": "Riordian",
        "spanish": "Riordian"
    },
    "saturas": {
        "brazilian": "Saturas",
        "english": "Saturas",
        "french": "Saturas",
        "german": "Saturas",
        "italian": "Saturas",
        "japanese": "Saturas",
        "polish": "Saturas",
        "russian": "Сатурас",
        "schinese": "Saturas",
        "spanish": "Saturas"
    },
    "gorn": {
        "brazilian": "Gorn",
        "english": "Gorn",
        "french": "Gorn",
        "german": "Gorn",
        "italian": "Gorn",
        "japanese": "Gorn",
        "polish": "Gorn",
        "russian": "Горн",
        "schinese": "Gorn",
        "spanish": "Gorn"
    },
    "lee": {
        "brazilian": "Lee",
        "english": "Lee",
        "french": "Lee",
        "german": "Lee",
        "italian": "Lee",
        "japanese": "Lee",
        "polish": "Lee",
        "russian": "Ли",
        "schinese": "Lee",
        "spanish": "Lee"
    },
    "rodriguez": {
        "brazilian": "Rodriguez",
        "english": "Rodriguez",
        "french": "Rodriguez",
        "german": "Rodriguez",
        "italian": "Rodriguez",
        "japanese": "Rodriguez",
        "polish": "Rodriguez",
        "russian": "Родригез",
        "schinese": "Rodriguez",
        "spanish": "Rodriguez"
    },
    "seraphia": {
        "brazilian": "Seraphia",
        "english": "Seraphia",
        "french": "Seraphia",
        "german": "Seraphia",
        "italian": "Seraphia",
        "japanese": "Seraphia",
        "polish": "Seraphia",
        "russian": "Серафия",
        "schinese": "Seraphia",
        "spanish": "Seraphia"
    },
    "syra": {
        "brazilian": "Syra",
        "english": "Syra",
        "french": "Syra",
        "german": "Syra",
        "italian": "Syra",
        "japanese": "Syra",
        "polish": "Syra",
        "russian": "Сира",
        "schinese": "Syra",
        "spanish": "Syra"
    },
    "velaya": {
        "brazilian": "Velaya",
        "english": "Velaya",
        "french": "Velaya",
        "german": "Velaya",
        "italian": "Velaya",
        "japanese": "Velaya",
        "polish": "Velaya",
        "russian": "Велая",
        "schinese": "Velaya",
        "spanish": "Velaya"
    },
    "baal_isidro": {
        "brazilian": "Baal Isidro",
        "english": "Baal Isidro",
        "french": "Baal Isidro",
        "german": "Baal Isidro",
        "italian": "Baal Isidro",
        "japanese": "Baal Isidro",
        "polish": "Baal Isidro",
        "russian": "Идол Исидро",
        "schinese": "Baal Isidro",
        "spanish": "Baal Isidro"
    },
    "baal_kagan": {
        "brazilian": "Baal Kagan",
        "english": "Baal Kagan",
        "french": "Baal Kagan",
        "german": "Baal Kagan",
        "italian": "Baal Kagan",
        "japanese": "Baal Kagan",
        "polish": "Baal Kagan",
        "russian": "Идол Каган",
        "schinese": "Baal Kagan",
        "spanish": "Baal Kagan"
    },
    "buster": {
        "brazilian": "Buster",
        "english": "Buster",
        "french": "Buster",
        "german": "Buster",
        "italian": "Buster",
        "japanese": "Buster",
        "polish": "Buster",
        "russian": "Бастер",
        "schinese": "Buster",
        "spanish": "Buster"
    },
    "butch": {
        "brazilian": "Butch",
        "english": "Butch",
        "french": "Butch",
        "german": "Butch",
        "italian": "Butch",
        "japanese": "Butch",
        "polish": "Butch",
        "russian": "Бутч",
        "schinese": "Butch",
        "spanish": "Butch"
    },
    "cipher": {
        "brazilian": "Cipher",
        "english": "Cipher",
        "french": "Cipher",
        "german": "Cipher",
        "italian": "Cipher",
        "japanese": "Cipher",
        "polish": "Cipher",
        "russian": "Сайфер",
        "schinese": "Cipher",
        "spanish": "Cipher"
    },
    "drax": {
        "brazilian": "Drax",
        "english": "Drax",
        "french": "Drax",
        "german": "Drax",
        "italian": "Drax",
        "japanese": "Drax",
        "polish": "Drax",
        "russian": "Дракс",
        "schinese": "Drax",
        "spanish": "Drax"
    },
    "lares": {
        "brazilian": "Lares",
        "english": "Lares",
        "french": "Lares",
        "german": "Lares",
        "italian": "Lares",
        "japanese": "Lares",
        "polish": "Lares",
        "russian": "Ларес",
        "schinese": "Lares",
        "spanish": "Lares"
    },
    "lefty": {
        "brazilian": "Lefty",
        "english": "Lefty",
        "french": "Lefty",
        "german": "Lefty",
        "italian": "Lefty",
        "japanese": "Lefty",
        "polish": "Lefty",
        "russian": "Лефти",
        "schinese": "Lefty",
        "spanish": "Lefty"
    },
    "roscoe": {
        "brazilian": "Roscoe",
        "english": "Roscoe",
        "french": "Roscoe",
        "german": "Roscoe",
        "italian": "Roscoe",
        "japanese": "Roscoe",
        "polish": "Roscoe",
        "russian": "Роско",
        "schinese": "Roscoe",
        "spanish": "Roscoe"
    },
    "wedge": {
        "brazilian": "Wedge",
        "english": "Wedge",
        "french": "Wedge",
        "german": "Wedge",
        "italian": "Wedge",
        "japanese": "Wedge",
        "polish": "Wedge",
        "russian": "Ведж",
        "schinese": "Wedge",
        "spanish": "Wedge"
    },
    "torlof": {
        "brazilian": "Torlof",
        "english": "Torlof",
        "french": "Torlof",
        "german": "Torlof",
        "italian": "Torlof",
        "japanese": "Torlof",
        "polish": "Torlof",
        "russian": "Торлоф",
        "schinese": "Torlof",
        "spanish": "Torlof"
    },
    "mordrag": {
        "brazilian": "Mordrag",
        "english": "Mordrag",
        "french": "Mordrag",
        "german": "Mordrag",
        "italian": "Mordrag",
        "japanese": "Mordrag",
        "polish": "Mordrag",
        "russian": "Мордраг",
        "schinese": "Mordrag",
        "spanish": "Mordrag"
    },
    "caine": {
        "brazilian": "Caine",
        "english": "Caine",
        "french": "Caine",
        "german": "Caine",
        "italian": "Caine",
        "japanese": "Caine",
        "polish": "Caine",
        "russian": "Каин",
        "schinese": "Caine",
        "spanish": "Caine"
    },
    "gor_na_drak": {
        "brazilian": "Gor Na Drak",
        "english": "Gor Na Drak",
        "french": "Gor Na Drak",
        "german": "Gor Na Drak",
        "italian": "Gor Na Drak",
        "japanese": "Gor Na Drak",
        "polish": "Gor Na Drak",
        "russian": "Гор На Драк",
        "schinese": "Gor Na Drak",
        "spanish": "Gor Na Drak"
    },
    "ratford": {
        "brazilian": "Ratford",
        "english": "Ratford",
        "french": "Ratford",
        "german": "Ratford",
        "italian": "Ratford",
        "japanese": "Ratford",
        "polish": "Ratford",
        "russian": "Рэтфорд",
        "schinese": "Ratford",
        "spanish": "Ratford"
    },
    "sharky": {
        "brazilian": "Sharky",
        "english": "Sharky",
        "french": "Sharky",
        "german": "Sharky",
        "italian": "Sharky",
        "japanese": "Sharky",
        "polish": "Sharky",
        "russian": "Шарки",
        "schinese": "Sharky",
        "spanish": "Sharky"
    },
    "shrike": {
        "brazilian": "Shrike",
        "english": "Shrike",
        "french": "Shrike",
        "german": "Shrike",
        "italian": "Shrike",
        "japanese": "Shrike",
        "polish": "Shrike",
        "russian": "Шрайк",
        "schinese": "Shrike",
        "spanish": "Shrike"
    },
    "silas": {
        "brazilian": "Silas",
        "english": "Silas",
        "french": "Silas",
        "german": "Silas",
        "italian": "Silas",
        "japanese": "Silas",
        "polish": "Silas",
        "russian": "Силас",
        "schinese": "Silas",
        "spanish": "Silas"
    },
    "ulmar": {
        "brazilian": "Ulmar",
        "english": "Ulmar",
        "french": "Ulmar",
        "german": "Ulmar",
        "italian": "Ulmar",
        "japanese": "Ulmar",
        "polish": "Ulmar",
        "russian": "Ульмар",
        "schinese": "Ulmar",
        "spanish": "Ulmar"
    },
    "wolf": {
        "brazilian": "Wolf",
        "english": "Wolf",
        "french": "Wolf",
        "german": "Wolf",
        "italian": "Wolf",
        "japanese": "Wolf",
        "polish": "Wolf",
        "russian": "Волк",
        "schinese": "Wolf",
        "spanish": "Wolf"
    },
    "cord": {
        "brazilian": "Cord",
        "english": "Cord",
        "french": "Cord",
        "german": "Cord",
        "italian": "Cord",
        "japanese": "Cord",
        "polish": "Cord",
        "russian": "Корд",
        "schinese": "Cord",
        "spanish": "Cord"
    },
    "the_sleeper": {
        "brazilian": "The Sleeper",
        "english": "The Sleeper",
        "french": "The Sleeper",
        "german": "The Sleeper",
        "italian": "The Sleeper",
        "japanese": "The Sleeper",
        "polish": "The Sleeper",
        "russian": "Спящий",
        "schinese": "The Sleeper",
        "spanish": "The Sleeper"
    },
    "jackal": {
        "brazilian": "Jackal",
        "english": "Jackal",
        "french": "Jackal",
        "german": "Jackal",
        "italian": "Jackal",
        "japanese": "Jackal",
        "polish": "Jackal",
        "russian": "Шакал",
        "schinese": "Jackal",
        "spanish": "Jackal"
    },
    "haenno": {
        "brazilian": "Haenno",
        "english": "Haenno",
        "french": "Haenno",
        "german": "Haenno",
        "italian": "Haenno",
        "japanese": "Haenno",
        "polish": "Haenno",
        "russian": "Хэнно",
        "schinese": "Haenno",
        "spanish": "Haenno"
    },
    "jarvis": {
        "brazilian": "Jarvis",
        "english": "Jarvis",
        "french": "Jarvis",
        "german": "Jarvis",
        "italian": "Jarvis",
        "japanese": "Jarvis",
        "polish": "Jarvis",
        "russian": "Ярвис",
        "schinese": "Jarvis",
        "spanish": "Jarvis"
    },
    "bloodwyn": {
        "brazilian": "Bloodwyn",
        "english": "Bloodwyn",
        "french": "Bloodwyn",
        "german": "Bloodwyn",
        "italian": "Bloodwyn",
        "japanese": "Bloodwyn",
        "polish": "Bloodwyn",
        "russian": "Бладвин",
        "schinese": "Bloodwyn",
        "spanish": "Bloodwyn"
    },
    "cutter": {
        "brazilian": "Cutter",
        "english": "Cutter",
        "french": "Cutter",
        "german": "Cutter",
        "italian": "Cutter",
        "japanese": "Cutter",
        "polish": "Cutter",
        "russian": "Каттер",
        "schinese": "Cutter",
        "spanish": "Cutter"
    },
    "dusty": {
        "brazilian": "Dusty",
        "english": "Dusty",
        "french": "Dusty",
        "german": "Dusty",
        "italian": "Dusty",
        "japanese": "Dusty",
        "polish": "Dusty",
        "russian": "Дасти",
        "schinese": "Dusty",
        "spanish": "Dusty"
    },
    "scatty": {
        "brazilian": "Scatty",
        "english": "Scatty",
        "french": "Scatty",
        "german": "Scatty",
        "italian": "Scatty",
        "japanese": "Scatty",
        "polish": "Scatty",
        "russian": "Скатти",
        "schinese": "Scatty",
        "spanish": "Scatty"
    },
    "kirgo": {
        "brazilian": "Kirgo",
        "english": "Kirgo",
        "french": "Kirgo",
        "german": "Kirgo",
        "italian": "Kirgo",
        "japanese": "Kirgo",
        "polish": "Kirgo",
        "russian": "Кирго",
        "schinese": "Kirgo",
        "spanish": "Kirgo"
    },
    "kharim": {
        "brazilian": "Kharim",
        "english": "Kharim",
        "french": "Kharim",
        "german": "Kharim",
        "italian": "Kharim",
        "japanese": "Kharim",
        "polish": "Kharim",
        "russian": "Харим",
        "schinese": "Kharim",
        "spanish": "Kharim"
    },
    "gor_hanis": {
        "brazilian": "Gor Hanis",
        "english": "Gor Hanis",
        "french": "Gor Hanis",
        "german": "Gor Hanis",
        "italian": "Gor Hanis",
        "japanese": "Gor Hanis",
        "polish": "Gor Hanis",
        "russian": "Гор Ханис",
        "schinese": "Gor Hanis",
        "spanish": "Gor Hanis"
    },
    "skip": {
        "brazilian": "Skip",
        "english": "Skip",
        "french": "Skip",
        "german": "Skip",
        "italian": "Skip",
        "japanese": "Skip",
        "polish": "Skip",
        "russian": "Скип",
        "schinese": "Skip",
        "spanish": "Skip"
    },
    "gor_na_zar": {
        "brazilian": "Gor Na Zar",
        "english": "Gor Na Zar",
        "french": "Gor Na Zar",
        "german": "Gor Na Zar",
        "italian": "Gor Na Zar",
        "japanese": "Gor Na Zar",
        "polish": "Gor Na Zar",
        "russian": "Гор На Зар",
        "schinese": "Gor Na Zar",
        "spanish": "Gor Na Zar"
    },
    "arto": {
        "brazilian": "Arto",
        "english": "Arto",
        "french": "Arto",
        "german": "Arto",
        "italian": "Arto",
        "japanese": "Arto",
        "polish": "Arto",
        "russian": "Арто",
        "schinese": "Arto",
        "spanish": "Arto"
    },
    "bartholo": {
        "brazilian": "Bartholo",
        "english": "Bartholo",
        "french": "Bartholo",
        "german": "Bartholo",
        "italian": "Bartholo",
        "japanese": "Bartholo",
        "polish": "Bartholo",
        "russian": "Бартоло",
        "schinese": "Bartholo",
        "spanish": "Bartholo"
    },
    "raven": {
        "brazilian": "Raven",
        "english": "Raven",
        "french": "Raven",
        "german": "Raven",
        "italian": "Raven",
        "japanese": "Raven",
        "polish": "Raven",
        "russian": "Ворон",
        "schinese": "Raven",
        "spanish": "Raven"
    },
    "torrez": {
        "brazilian": "Torrez",
        "english": "Torrez",
        "french": "Torrez",
        "german": "Torrez",
        "italian": "Torrez",
        "japanese": "Torrez",
        "polish": "Torrez",
        "russian": "Торрез",
        "schinese": "Torrez",
        "spanish": "Torrez"
    },
    "scar": {
        "brazilian": "Scar",
        "english": "Scar",
        "french": "Scar",
        "german": "Scar",
        "italian": "Scar",
        "japanese": "Scar",
        "polish": "Scar",
        "russian": "Шрам",
        "schinese": "Scar",
        "spanish": "Scar"
    },
    "fletcher": {
        "brazilian": "Fletcher",
        "english": "Fletcher",
        "french": "Fletcher",
        "german": "Fletcher",
        "italian": "Fletcher",
        "japanese": "Fletcher",
        "polish": "Fletcher",
        "russian": "Флетчер",
        "schinese": "Fletcher",
        "spanish": "Fletcher"
    },
    "orry": {
        "brazilian": "Orry",
        "english": "Orry",
        "french": "Orry",
        "german": "Orry",
        "italian": "Orry",
        "japanese": "Orry",
        "polish": "Orry",
        "russian": "Орри",
        "schinese": "Orry",
        "spanish": "Orry"
    },
    "pacho": {
        "brazilian": "Pacho",
        "english": "Pacho",
        "french": "Pacho",
        "german": "Pacho",
        "italian": "Pacho",
        "japanese": "Pacho",
        "polish": "Pacho",
        "russian": "Пачо",
        "schinese": "Pacho",
        "spanish": "Pacho"
    },
    "scorpio": {
        "brazilian": "Scorpio",
        "english": "Scorpio",
        "french": "Scorpio",
        "german": "Scorpio",
        "italian": "Scorpio",
        "japanese": "Scorpio",
        "polish": "Scorpio",
        "russian": "Скорпио",
        "schinese": "Scorpio",
        "spanish": "Scorpio"
    },
    "thorus": {
        "brazilian": "Thorus",
        "english": "Thorus",
        "french": "Thorus",
        "german": "Thorus",
        "italian": "Thorus",
        "japanese": "Thorus",
        "polish": "Thorus",
        "russian": "Торус",
        "schinese": "Thorus",
        "spanish": "Thorus"
    },
    "charlotte": {
        "brazilian": "Charlotte",
        "english": "Charlotte",
        "french": "Charlotte",
        "german": "Charlotte",
        "italian": "Charlotte",
        "japanese": "Charlotte",
        "polish": "Charlotte",
        "russian": "Шарлотта",
        "schinese": "Charlotte",
        "spanish": "Charlotte"
    },
    "dr_pymonte": {
        "brazilian": "Dr. Pymonte",
        "english": "Dr. Pymonte",
        "french": "Dr. Pymonte",
        "german": "Dr. Pymonte",
        "italian": "Dr. Pymonte",
        "japanese": "Dr. Pymonte",
        "polish": "Dr. Pymonte",
        "russian": "Dr. Pymonte",
        "schinese": "Dr. Pymonte",
        "spanish": "Dr. Pymonte"
    },
    "flex_der_biegsame": {
        "brazilian": "Flex der Biegsame",
        "english": "Flex der Biegsame",
        "french": "Flex der Biegsame",
        "german": "Flex der Biegsame",
        "italian": "Flex der Biegsame",
        "japanese": "Flex der Biegsame",
        "polish": "Flex der Biegsame",
        "russian": "Flex der Biegsame",
        "schinese": "Flex der Biegsame",
        "spanish": "Flex der Biegsame"
    },
    "die_lutte": {
        "brazilian": "Die Lutte",
        "english": "Die Lutte",
        "french": "Die Lutte",
        "german": "Die Lutte",
        "italian": "Die Lutte",
        "japanese": "Die Lutte",
        "polish": "Die Lutte",
        "russian": "Die Lutte",
        "schinese": "Die Lutte",
        "spanish": "Die Lutte"
    },
    "specki_td": {
        "brazilian": "Specki T.D.",
        "english": "Specki T.D.",
        "french": "Specki T.D.",
        "german": "Specki T.D.",
        "italian": "Specki T.D.",
        "japanese": "Specki T.D.",
        "polish": "Specki T.D.",
        "russian": "Specki T.D.",
        "schinese": "Specki T.D.",
        "spanish": "Specki T.D."
    },
    "steve": {
        "brazilian": "Steve",
        "english": "Steve",
        "french": "Steve",
        "german": "Steve",
        "italian": "Steve",
        "japanese": "Steve",
        "polish": "Steve",
        "russian": "Стив",
        "schinese": "Steve",
        "spanish": "Steve"
    },
    "das_letzte_einhorn": {
        "brazilian": "Das Letzte Einhorn",
        "english": "Das Letzte Einhorn",
        "french": "Das Letzte Einhorn",
        "german": "Das Letzte Einhorn",
        "italian": "Das Letzte Einhorn",
        "japanese": "Das Letzte Einhorn",
        "polish": "Das Letzte Einhorn",
        "russian": "Das Letzte Einhorn",
        "schinese": "Das Letzte Einhorn",
        "spanish": "Das Letzte Einhorn"
    },
    "van_lange": {
        "brazilian": "Van Lange",
        "english": "Van Lange",
        "french": "Van Lange",
        "german": "Van Lange",
        "italian": "Van Lange",
        "japanese": "Van Lange",
        "polish": "Van Lange",
        "russian": "Van Lange",
        "schinese": "Van Lange",
        "spanish": "Van Lange"
    },
    "damarok": {
        "brazilian": "Damarok",
        "english": "Damarok",
        "french": "Damarok",
        "german": "Damarok",
        "italian": "Damarok",
        "japanese": "Damarok",
        "polish": "Damarok",
        "russian": "Дамарок",
        "schinese": "Damarok",
        "spanish": "Damarok"
    },
    "drago": {
        "brazilian": "Drago",
        "english": "Drago",
        "french": "Drago",
        "german": "Drago",
        "italian": "Drago",
        "japanese": "Drago",
        "polish": "Drago",
        "russian": "Драго",
        "schinese": "Drago",
        "spanish": "Drago"
    },
    "chani": {
        "brazilian": "Chani",
        "english": "Chani",
        "french": "Chani",
        "german": "Chani",
        "italian": "Chani",
        "japanese": "Chani",
        "polish": "Chani",
        "russian": "Чани",
        "schinese": "Chani",
        "spanish": "Chani"
    },
    "natalia": {
        "brazilian": "Natalia",
        "english": "Natalia",
        "french": "Natalia",
        "german": "Natalia",
        "italian": "Natalia",
        "japanese": "Natalia",
        "polish": "Natalia",
        "russian": "Наталья",
        "schinese": "Natalia",
        "spanish": "Natalia"
    },
    "baal_parvez": {
        "brazilian": "Baal Parvez",
        "english": "Baal Parvez",
        "french": "Baal Parvez",
        "german": "Baal Parvez",
        "italian": "Baal Parvez",
        "japanese": "Baal Parvez",
        "polish": "Baal Parvez",
        "russian": "Идол Парвез",
        "schinese": "Baal Parvez",
        "spanish": "Baal Parvez"
    },
    "baal_taran": {
        "brazilian": "Baal Taran",
        "english": "Baal Taran",
        "french": "Baal Taran",
        "german": "Baal Taran",
        "italian": "Baal Taran",
        "japanese": "Baal Taran",
        "polish": "Baal Taran",
        "russian": "Идол Таран",
        "schinese": "Baal Taran",
        "spanish": "Baal Taran"
    },
    "dexter": {
        "brazilian": "Dexter",
        "english": "Dexter",
        "french": "Dexter",
        "german": "Dexter",
        "italian": "Dexter",
        "japanese": "Dexter",
        "polish": "Dexter",
        "russian": "Декстер",
        "schinese": "Dexter",
        "spanish": "Dexter"
    },
    "fingers": {
        "brazilian": "Fingers",
        "english": "Fingers",
        "french": "Fingers",
        "german": "Fingers",
        "italian": "Fingers",
        "japanese": "Fingers",
        "polish": "Fingers",
        "russian": "Фингерс",
        "schinese": "Fingers",
        "spanish": "Fingers"
    },
    "fisk": {
        "brazilian": "Fisk",
        "english": "Fisk",
        "french": "Fisk",
        "german": "Fisk",
        "italian": "Fisk",
        "japanese": "Fisk",
        "polish": "Fisk",
        "russian": "Фиск",
        "schinese": "Fisk",
        "spanish": "Fisk"
    },
    "sly": {
        "brazilian": "Sly",
        "english": "Sly",
        "french": "Sly",
        "german": "Sly",
        "italian": "Sly",
        "japanese": "Sly",
        "polish": "Sly",
        "russian": "Слай",
        "schinese": "Sly",
        "spanish": "Sly"
    },
    "whistler": {
        "brazilian": "Whistler",
        "english": "Whistler",
        "french": "Whistler",
        "german": "Whistler",
        "italian": "Whistler",
        "japanese": "Whistler",
        "polish": "Whistler",
        "russian": "Уистлер",
        "schinese": "Whistler",
        "spanish": "Whistler"
    },
    "ian": {
        "brazilian": "Ian",
        "english": "Ian",
        "french": "Ian",
        "german": "Ian",
        "italian": "Ian",
        "japanese": "Ian",
        "polish": "Ian",
        "russian": "Ян",
        "schinese": "Ian",
        "spanish": "Ian"
    },
    "baal_tondral": {
        "brazilian": "Baal Tondral",
        "english": "Baal Tondral",
        "french": "Baal Tondral",
        "german": "Baal Tondral",
        "italian": "Baal Tondral",
        "japanese": "Baal Tondral",
        "polish": "Baal Tondral",
        "russian": "Идол Тондрал",
        "schinese": "Baal Tondral",
        "spanish": "Baal Tondral"
    },
    "melvin": {
        "brazilian": "Melvin",
        "english": "Melvin",
        "french": "Melvin",
        "german": "Melvin",
        "italian": "Melvin",
        "japanese": "Melvin",
        "polish": "Melvin",
        "russian": "Мелвин",
        "schinese": "Melvin",
        "spanish": "Melvin"
    },
    "graham": {
        "brazilian": "Graham",
        "english": "Graham",
        "french": "Graham",
        "german": "Graham",
        "italian": "Graham",
        "japanese": "Graham",
        "polish": "Graham",
        "russian": "Грэхем",
        "schinese": "Graham",
        "spanish": "Graham"
    },
    "gravo": {
        "brazilian": "Gravo",
        "english": "Gravo",
        "french": "Gravo",
        "german": "Gravo",
        "italian": "Gravo",
        "japanese": "Gravo",
        "polish": "Gravo",
        "russian": "Граво",
        "schinese": "Gravo",
        "spanish": "Gravo"
    },
    "grim": {
        "brazilian": "Grim",
        "english": "Grim",
        "french": "Grim",
        "german": "Grim",
        "italian": "Grim",
        "japanese": "Grim",
        "polish": "Grim",
        "russian": "Грим",
        "schinese": "Grim",
        "spanish": "Grim"
    },
    "guy": {
        "brazilian": "Guy",
        "english": "Guy",
        "french": "Guy",
        "german": "Guy",
        "italian": "Guy",
        "japanese": "Guy",
        "polish": "Guy",
        "russian": "Гай",
        "schinese": "Guy",
        "spanish": "Guy"
    },
    "herek": {
        "brazilian": "Herek",
        "english": "Herek",
        "french": "Herek",
        "german": "Herek",
        "italian": "Herek",
        "japanese": "Herek",
        "polish": "Herek",
        "russian": "Херек",
        "schinese": "Herek",
        "spanish": "Herek"
    },
    "huno": {
        "brazilian": "Huno",
        "english": "Huno",
        "french": "Huno",
        "german": "Huno",
        "italian": "Huno",
        "japanese": "Huno",
        "polish": "Huno",
        "russian": "Хуно",
        "schinese": "Huno",
        "spanish": "Huno"
    },
    "jesse": {
        "brazilian": "Jesse",
        "english": "Jesse",
        "french": "Jesse",
        "german": "Jesse",
        "italian": "Jesse",
        "japanese": "Jesse",
        "polish": "Jesse",
        "russian": "Джесс",
        "schinese": "Jesse",
        "spanish": "Jesse"
    },
    "kyle": {
        "brazilian": "Kyle",
        "english": "Kyle",
        "french": "Kyle",
        "german": "Kyle",
        "italian": "Kyle",
        "japanese": "Kyle",
        "polish": "Kyle",
        "russian": "Кайл",
        "schinese": "Kyle",
        "spanish": "Kyle"
    },
    "mad_mud": {
        "brazilian": "Mad Mud",
        "english": "Mad Mud",
        "french": "Mad Mud",
        "german": "Mad Mud",
        "italian": "Mad Mud",
        "japanese": "Mad Mud",
        "polish": "Mad Mud",
        "russian": "Безумный Мад",
        "schinese": "Mad Mud",
        "spanish": "Mad Mud"
    },
    "snaf": {
        "brazilian": "Snaf",
        "english": "Snaf",
        "french": "Snaf",
        "german": "Snaf",
        "italian": "Snaf",
        "japanese": "Snaf",
        "polish": "Snaf",
        "russian": "Снаф",
        "schinese": "Snaf",
        "spanish": "Snaf"
    },
    "aaron": {
        "brazilian": "Aaron",
        "english": "Aaron",
        "french": "Aaron",
        "german": "Aaron",
        "italian": "Aaron",
        "japanese": "Aaron",
        "polish": "Aaron",
        "russian": "Арон",
        "schinese": "Aaron",
        "spanish": "Aaron"
    },
    "asghan": {
        "brazilian": "Asghan",
        "english": "Asghan",
        "french": "Asghan",
        "german": "Asghan",
        "italian": "Asghan",
        "japanese": "Asghan",
        "polish": "Asghan",
        "russian": "Асган",
        "schinese": "Asghan",
        "spanish": "Asghan"
    },
    "gor_na_bar": {
        "brazilian": "Gor Na Bar",
        "english": "Gor Na Bar",
        "french": "Gor Na Bar",
        "german": "Gor Na Bar",
        "italian": "Gor Na Bar",
        "japanese": "Gor Na Bar",
        "polish": "Gor Na Bar",
        "russian": "Гор На Бар",
        "schinese": "Gor Na Bar",
        "spanish": "Gor Na Bar"
    },
    "gor_na_kosh": {
        "brazilian": "Gor Na Kosh",
        "english": "Gor Na Kosh",
        "french": "Gor Na Kosh",
        "german": "Gor Na Kosh",
        "italian": "Gor Na Kosh",
        "japanese": "Gor Na Kosh",
        "polish": "Gor Na Kosh",
        "russian": "Гор На Кош",
        "schinese": "Gor Na Kosh",
        "spanish": "Gor Na Kosh"
    },
    "gor_na_vid": {
        "brazilian": "Gor Na Vid",
        "english": "Gor Na Vid",
        "french": "Gor Na Vid",
        "german": "Gor Na Vid",
        "italian": "Gor Na Vid",
        "japanese": "Gor Na Vid",
        "polish": "Gor Na Vid",
        "russian": "Гор На Вид",
        "schinese": "Gor Na Vid",
        "spanish": "Gor Na Vid"
    },
    "brandick": {
        "brazilian": "Brandick",
        "english": "Brandick",
        "french": "Brandick",
        "german": "Brandick",
        "italian": "Brandick",
        "japanese": "Brandick",
        "polish": "Brandick",
        "russian": "Брендик",
        "schinese": "Brandick",
        "spanish": "Brandick"
    },
    "drake": {
        "brazilian": "Drake",
        "english": "Drake",
        "french": "Drake",
        "german": "Drake",
        "italian": "Drake",
        "japanese": "Drake",
        "polish": "Drake",
        "russian": "Дрейк",
        "schinese": "Drake",
        "spanish": "Drake"
    },
    "ulbert": {
        "brazilian": "Ulbert",
        "english": "Ulbert",
        "french": "Ulbert",
        "german": "Ulbert",
        "italian": "Ulbert",
        "japanese": "Ulbert",
        "polish": "Ulbert",
        "russian": "Ульберт",
        "schinese": "Ulbert",
        "spanish": "Ulbert"
    },
    "alberto": {
        "brazilian": "Alberto",
        "english": "Alberto",
        "french": "Alberto",
        "german": "Alberto",
        "italian": "Alberto",
        "japanese": "Alberto",
        "polish": "Alberto",
        "russian": "Альберто",
        "schinese": "Alberto",
        "spanish": "Alberto"
    },
    "santino": {
        "brazilian": "Santino",
        "english": "Santino",
        "french": "Santino",
        "german": "Santino",
        "italian": "Santino",
        "japanese": "Santino",
        "polish": "Santino",
        "russian": "Сантино",
        "schinese": "Santino",
        "spanish": "Santino"
    },
    "viper": {
        "brazilian": "Viper",
        "english": "Viper",
        "french": "Viper",
        "german": "Viper",
        "italian": "Viper",
        "japanese": "Viper",
        "polish": "Viper",
        "russian": "Вайпер",
        "schinese": "Viper",
        "spanish": "Viper"
    },
    "aleph": {
        "brazilian": "Aleph",
        "english": "Aleph",
        "french": "Aleph",
        "german": "Aleph",
        "italian": "Aleph",
        "japanese": "Aleph",
        "polish": "Aleph",
        "russian": "Алеф",
        "schinese": "Aleph",
        "spanish": "Aleph"
    },
    "garp": {
        "brazilian": "Garp",
        "english": "Garp",
        "french": "Garp",
        "german": "Garp",
        "italian": "Garp",
        "japanese": "Garp",
        "polish": "Garp",
        "russian": "Гарп",
        "schinese": "Garp",
        "spanish": "Garp"
    },
    "glen": {
        "brazilian": "Glen",
        "english": "Glen",
        "french": "Glen",
        "german": "Glen",
        "italian": "Glen",
        "japanese": "Glen",
        "polish": "Glen",
        "russian": "Глен",
        "schinese": "Glen",
        "spanish": "Glen"
    },
    "grimes": {
        "brazilian": "Grimes",
        "english": "Grimes",
        "french": "Grimes",
        "german": "Grimes",
        "italian": "Grimes",
        "japanese": "Grimes",
        "polish": "Grimes",
        "russian": "Граймс",
        "schinese": "Grimes",
        "spanish": "Grimes"
    },
    "snipes": {
        "brazilian": "Snipes",
        "english": "Snipes",
        "french": "Snipes",
        "german": "Snipes",
        "italian": "Snipes",
        "japanese": "Snipes",
        "polish": "Snipes",
        "russian": "Снайпс",
        "schinese": "Snipes",
        "spanish": "Snipes"
    },
    "ur_nazkrog": {
        "brazilian": "Ur-Nazkrog",
        "english": "Ur-Nazkrog",
        "french": "Ur-Nazkrog",
        "german": "Ur-Nazkrog",
        "italian": "Ur-Nazkrog",
        "japanese": "Ur-Nazkrog",
        "polish": "Ur-Nazkrog",
        "russian": "Ур-Назкрог",
        "schinese": "Ur-Nazkrog",
        "spanish": "Ur-Nazkrog"
    },
    "umosh": {
        "brazilian": "Umosh",
        "english": "Umosh",
        "french": "Umosh",
        "german": "Umosh",
        "italian": "Umosh",
        "japanese": "Umosh",
        "polish": "Umosh",
        "russian": "Умош",
        "schinese": "Umosh",
        "spanish": "Umosh"
    },
    "chokta": {
        "brazilian": "Chokta",
        "english": "Chokta",
        "french": "Chokta",
        "german": "Chokta",
        "italian": "Chokta",
        "japanese": "Chokta",
        "polish": "Chokta",
        "russian": "Чокта",
        "schinese": "Chokta",
        "spanish": "Chokta"
    },
    "fire_lizard": {
        "brazilian": "Fire Lizard",
        "english": "Fire Lizard",
        "french": "Fire Lizard",
        "german": "Fire Lizard",
        "italian": "Fire Lizard",
        "japanese": "Fire Lizard",
        "polish": "Fire Lizard",
        "russian": "Огненный ящер",
        "schinese": "Fire Lizard",
        "spanish": "Fire Lizard"
    },
    "ur_shak": {
        "brazilian": "Ur-Shak",
        "english": "Ur-Shak",
        "french": "Ur-Shak",
        "german": "Ur-Shak",
        "italian": "Ur-Shak",
        "japanese": "Ur-Shak",
        "polish": "Ur-Shak",
        "russian": "Ур-Шак",
        "schinese": "Ur-Shak",
        "spanish": "Ur-Shak"
    },
    "krashok": {
        "brazilian": "Krashok",
        "english": "Krashok",
        "french": "Krashok",
        "german": "Krashok",
        "italian": "Krashok",
        "japanese": "Krashok",
        "polish": "Krashok",
        "russian": "Крашок",
        "schinese": "Krashok",
        "spanish": "Krashok"
    },
    "questdealer": {
        "brazilian": "Questdealer",
        "english": "Questdealer",
        "french": "Questdealer",
        "german": "Questdealer",
        "italian": "Questdealer",
        "japanese": "Questdealer",
        "polish": "Questdealer",
        "russian": "Questdealer",
        "schinese": "Questdealer",
        "spanish": "Questdealer"
    },
    "baal_cadar": {
        "brazilian": "Baal Cadar",
        "english": "Baal Cadar",
        "french": "Baal Cadar",
        "german": "Baal Cadar",
        "italian": "Baal Cadar",
        "japanese": "Baal Cadar",
        "polish": "Baal Cadar",
        "russian": "Идол Кадар",
        "schinese": "Baal Cadar",
        "spanish": "Baal Cadar"
    },
    "baal_namib": {
        "brazilian": "Baal Namib",
        "english": "Baal Namib",
        "french": "Baal Namib",
        "german": "Baal Namib",
        "italian": "Baal Namib",
        "japanese": "Baal Namib",
        "polish": "Baal Namib",
        "russian": "Идол Намиб",
        "schinese": "Baal Namib",
        "spanish": "Baal Namib"
    },
    "baal_orun": {
        "brazilian": "Baal Orun",
        "english": "Baal Orun",
        "french": "Baal Orun",
        "german": "Baal Orun",
        "italian": "Baal Orun",
        "japanese": "Baal Orun",
        "polish": "Baal Orun",
        "russian": "Идол Оран",
        "schinese": "Baal Orun",
        "spanish": "Baal Orun"
    },
    "baal_tyon": {
        "brazilian": "Baal Tyon",
        "english": "Baal Tyon",
        "french": "Baal Tyon",
        "german": "Baal Tyon",
        "italian": "Baal Tyon",
        "japanese": "Baal Tyon",
        "polish": "Baal Tyon",
        "russian": "Идол Тион",
        "schinese": "Baal Tyon",
        "spanish": "Baal Tyon"
    },
    "ghorim": {
        "brazilian": "Ghorim",
        "english": "Ghorim",
        "french": "Ghorim",
        "german": "Ghorim",
        "italian": "Ghorim",
        "japanese": "Ghorim",
        "polish": "Ghorim",
        "russian": "Горрим",
        "schinese": "Ghorim",
        "spanish": "Ghorim"
    },
    "gor_na_dun": {
        "brazilian": "Gor Na Dun",
        "english": "Gor Na Dun",
        "french": "Gor Na Dun",
        "german": "Gor Na Dun",
        "italian": "Gor Na Dun",
        "japanese": "Gor Na Dun",
        "polish": "Gor Na Dun",
        "russian": "Гор На Дан",
        "schinese": "Gor Na Dun",
        "spanish": "Gor Na Dun"
    },
    "jacko": {
        "brazilian": "Jacko",
        "english": "Jacko",
        "french": "Jacko",
        "german": "Jacko",
        "italian": "Jacko",
        "japanese": "Jacko",
        "polish": "Jacko",
        "russian": "Джако",
        "schinese": "Jacko",
        "spanish": "Jacko"
    },
    "renyu": {
        "brazilian": "Renyu",
        "english": "Renyu",
        "french": "Renyu",
        "german": "Renyu",
        "italian": "Renyu",
        "japanese": "Renyu",
        "polish": "Renyu",
        "russian": "Рену",
        "schinese": "Renyu",
        "spanish": "Renyu"
    },
    "talas": {
        "brazilian": "Talas",
        "english": "Talas",
        "french": "Talas",
        "german": "Talas",
        "italian": "Talas",
        "japanese": "Talas",
        "polish": "Talas",
        "russian": "Талас",
        "schinese": "Talas",
        "spanish": "Talas"
    },
    "baal_netbek": {
        "brazilian": "Baal Netbek",
        "english": "Baal Netbek",
        "french": "Baal Netbek",
        "german": "Baal Netbek",
        "italian": "Baal Netbek",
        "japanese": "Baal Netbek",
        "polish": "Baal Netbek",
        "russian": "Идол Нетбек",
        "schinese": "Baal Netbek",
        "spanish": "Baal Netbek"
    },
    "balor": {
        "brazilian": "Balor",
        "english": "Balor",
        "french": "Balor",
        "german": "Balor",
        "italian": "Balor",
        "japanese": "Balor",
        "polish": "Balor",
        "russian": "Балор",
        "schinese": "Balor",
        "spanish": "Balor"
    },
    "darrion": {
        "brazilian": "Darrion",
        "english": "Darrion",
        "french": "Darrion",
        "german": "Darrion",
        "italian": "Darrion",
        "japanese": "Darrion",
        "polish": "Darrion",
        "russian": "Даррион",
        "schinese": "Darrion",
        "spanish": "Darrion"
    },
    "fortuno": {
        "brazilian": "Fortuno",
        "english": "Fortuno",
        "french": "Fortuno",
        "german": "Fortuno",
        "italian": "Fortuno",
        "japanese": "Fortuno",
        "polish": "Fortuno",
        "russian": "Фортуно",
        "schinese": "Fortuno",
        "spanish": "Fortuno"
    },
    "harlok": {
        "brazilian": "Harlok",
        "english": "Harlok",
        "french": "Harlok",
        "german": "Harlok",
        "italian": "Harlok",
        "japanese": "Harlok",
        "polish": "Harlok",
        "russian": "Харлок",
        "schinese": "Harlok",
        "spanish": "Harlok"
    },
    "shrat": {
        "brazilian": "Shrat",
        "english": "Shrat",
        "french": "Shrat",
        "german": "Shrat",
        "italian": "Shrat",
        "japanese": "Shrat",
        "polish": "Shrat",
        "russian": "Шрет",
        "schinese": "Shrat",
        "spanish": "Shrat"
    },
    "theron": {
        "brazilian": "Theron",
        "english": "Theron",
        "french": "Theron",
        "german": "Theron",
        "italian": "Theron",
        "japanese": "Theron",
        "polish": "Theron",
        "russian": "Терон",
        "schinese": "Theron",
        "spanish": "Theron"
    },
    "viran": {
        "brazilian": "Viran",
        "english": "Viran",
        "french": "Viran",
        "german": "Viran",
        "italian": "Viran",
        "japanese": "Viran",
        "polish": "Viran",
        "russian": "Вайран",
        "schinese": "Viran",
        "spanish": "Viran"
    },
    "gor_na_ran": {
        "brazilian": "Gor Na Ran",
        "english": "Gor Na Ran",
        "french": "Gor Na Ran",
        "german": "Gor Na Ran",
        "italian": "Gor Na Ran",
        "japanese": "Gor Na Ran",
        "polish": "Gor Na Ran",
        "russian": "Гор На Ран",
        "schinese": "Gor Na Ran",
        "spanish": "Gor Na Ran"
    },
    "gor_na_toth": {
        "brazilian": "Gor Na Toth",
        "english": "Gor Na Toth",
        "french": "Gor Na Toth",
        "german": "Gor Na Toth",
        "italian": "Gor Na Toth",
        "japanese": "Gor Na Toth",
        "polish": "Gor Na Toth",
        "russian": "Гор На Тоф",
        "schinese": "Gor Na Toth",
        "spanish": "Gor Na Toth"
    },
    "mad_cor_kalom": {
        "brazilian": "Mad Cor Kalom",
        "english": "Mad Cor Kalom",
        "french": "Mad Cor Kalom",
        "german": "Mad Cor Kalom",
        "italian": "Mad Cor Kalom",
        "japanese": "Mad Cor Kalom",
        "polish": "Mad Cor Kalom",
        "russian": "Безумный Кор Галом",
        "schinese": "Mad Cor Kalom",
        "spanish": "Mad Cor Kalom"
    },
    "gor_boba": {
        "brazilian": "Gor Boba",
        "english": "Gor Boba",
        "french": "Gor Boba",
        "german": "Gor Boba",
        "italian": "Gor Boba",
        "japanese": "Gor Boba",
        "polish": "Gor Boba",
        "russian": "Гор Боба",
        "schinese": "Gor Boba",
        "spanish": "Gor Boba"
    },
    "varrag_unhilqt": {
        "brazilian": "Varrag Unhilqt",
        "english": "Varrag Unhilqt",
        "french": "Varrag Unhilqt",
        "german": "Varrag Unhilqt",
        "italian": "Varrag Unhilqt",
        "japanese": "Varrag Unhilqt",
        "polish": "Varrag Unhilqt",
        "russian": "Варраг-Унхилькт",
        "schinese": "Varrag Unhilqt",
        "spanish": "Varrag Unhilqt"
    },
    "varrag_arushat": {
        "brazilian": "Varrag Arushat",
        "english": "Varrag Arushat",
        "french": "Varrag Arushat",
        "german": "Varrag Arushat",
        "italian": "Varrag Arushat",
        "japanese": "Varrag Arushat",
        "polish": "Varrag Arushat",
        "russian": "Варраг-Арушат",
        "schinese": "Varrag Arushat",
        "spanish": "Varrag Arushat"
    },
    "varrag_hashor": {
        "brazilian": "Varrag Hashor",
        "english": "Varrag Hashor",
        "french": "Varrag Hashor",
        "german": "Varrag Hashor",
        "italian": "Varrag Hashor",
        "japanese": "Varrag Hashor",
        "polish": "Varrag Hashor",
        "russian": "Варраг-Хашор",
        "schinese": "Varrag Hashor",
        "spanish": "Varrag Hashor"
    },
    "varrag_kasorg": {
        "brazilian": "Varrag Kasorg",
        "english": "Varrag Kasorg",
        "french": "Varrag Kasorg",
        "german": "Varrag Kasorg",
        "italian": "Varrag Kasorg",
        "japanese": "Varrag Kasorg",
        "polish": "Varrag Kasorg",
        "russian": "Варраг-Казорг",
        "schinese": "Varrag Kasorg",
        "spanish": "Varrag Kasorg"
    },
    "varrag_ruuushk": {
        "brazilian": "Varrag Ruuushk",
        "english": "Varrag Ruuushk",
        "french": "Varrag Ruuushk",
        "german": "Varrag Ruuushk",
        "italian": "Varrag Ruuushk",
        "japanese": "Varrag Ruuushk",
        "polish": "Varrag Ruuushk",
        "russian": "Варраг-Руушк",
        "schinese": "Varrag Ruuushk",
        "spanish": "Varrag Ruuushk"
    },
    "gilbert": {
        "brazilian": "Gilbert",
        "english": "Gilbert",
        "french": "Gilbert",
        "german": "Gilbert",
        "italian": "Gilbert",
        "japanese": "Gilbert",
        "polish": "Gilbert",
        "russian": "Гилберт",
        "schinese": "Gilbert",
        "spanish": "Gilbert"
    },
    "aidan": {
        "brazilian": "Aidan",
        "english": "Aidan",
        "french": "Aidan",
        "german": "Aidan",
        "italian": "Aidan",
        "japanese": "Aidan",
        "polish": "Aidan",
        "russian": "Эйдан",
        "schinese": "Aidan",
        "spanish": "Aidan"
    },
    "blackmailer": {
        "brazilian": "Blackmailer",
        "english": "Blackmailer",
        "french": "Blackmailer",
        "german": "Blackmailer",
        "italian": "Blackmailer",
        "japanese": "Blackmailer",
        "polish": "Blackmailer",
        "russian": "Вымогатель",
        "schinese": "Blackmailer",
        "spanish": "Blackmailer"
    },
    "cavalorn": {
        "brazilian": "Cavalorn",
        "english": "Cavalorn",
        "french": "Cavalorn",
        "german": "Cavalorn",
        "italian": "Cavalorn",
        "japanese": "Cavalorn",
        "polish": "Cavalorn",
        "russian": "Кавалорн",
        "schinese": "Cavalorn",
        "spanish": "Cavalorn"
    },
    "cohsel": {
        "brazilian": "Cohsel",
        "english": "Cohsel",
        "french": "Cohsel",
        "german": "Cohsel",
        "italian": "Cohsel",
        "japanese": "Cohsel",
        "polish": "Cohsel",
        "russian": "Косель",
        "schinese": "Cohsel",
        "spanish": "Cohsel"
    },
    "unittest": {
        "brazilian": "Unittest",
        "english": "Unittest",
        "french": "Unittest",
        "german": "Unittest",
        "italian": "Unittest",
        "japanese": "Unittest",
        "polish": "Unittest",
        "russian": "Unittest",
        "schinese": "Unittest",
        "spanish": "Unittest"
    },
    "xardas_demon": {
        "brazilian": "Xardas Demon",
        "english": "Xardas Demon",
        "french": "Xardas Demon",
        "german": "Xardas Demon",
        "italian": "Xardas Demon",
        "japanese": "Xardas Demon",
        "polish": "Xardas Demon",
        "russian": "Демон Ксардаса",
        "schinese": "Xardas Demon",
        "spanish": "Xardas Demon"
    },
    "angar": {
        "brazilian": "Angar",
        "english": "Angar",
        "french": "Angar",
        "german": "Angar",
        "italian": "Angar",
        "japanese": "Angar",
        "polish": "Angar",
        "russian": "Ангар",
        "schinese": "Angar",
        "spanish": "Angar"
    },
    "baalcadar_old": {
        "brazilian": "Baal Cadar",
        "english": "Baal Cadar",
        "french": "Baal Cadar",
        "german": "Baal Cadar",
        "italian": "Baal Cadar",
        "japanese": "Baal Cadar",
        "polish": "Baal Cadar",
        "russian": "Идол Кадар",
        "schinese": "Baal Cadar",
        "spanish": "Baal Cadar"
    },
    "baalisidro_old": {
        "brazilian": "Baal Isidro",
        "english": "Baal Isidro",
        "french": "Baal Isidro",
        "german": "Baal Isidro",
        "italian": "Baal Isidro",
        "japanese": "Baal Isidro",
        "polish": "Baal Isidro",
        "russian": "Идол Исидро",
        "schinese": "Baal Isidro",
        "spanish": "Baal Isidro"
    },
    "baalkagan_old": {
        "brazilian": "Baal Kagan",
        "english": "Baal Kagan",
        "french": "Baal Kagan",
        "german": "Baal Kagan",
        "italian": "Baal Kagan",
        "japanese": "Baal Kagan",
        "polish": "Baal Kagan",
        "russian": "Идол Каган",
        "schinese": "Baal Kagan",
        "spanish": "Baal Kagan"
    },
    "baallukor_old": {
        "brazilian": "Baal Lukor",
        "english": "Baal Lukor",
        "french": "Baal Lukor",
        "german": "Baal Lukor",
        "italian": "Baal Lukor",
        "japanese": "Baal Lukor",
        "polish": "Baal Lukor",
        "russian": "Идол Люкор",
        "schinese": "Baal Lukor",
        "spanish": "Baal Lukor"
    },
    "baalnamib_old": {
        "brazilian": "Baal Namib",
        "english": "Baal Namib",
        "french": "Baal Namib",
        "german": "Baal Namib",
        "italian": "Baal Namib",
        "japanese": "Baal Namib",
        "polish": "Baal Namib",
        "russian": "Идол Намиб",
        "schinese": "Baal Namib",
        "spanish": "Baal Namib"
    },
    "baalnetbek_old": {
        "brazilian": "Baal Netbek",
        "english": "Baal Netbek",
        "french": "Baal Netbek",
        "german": "Baal Netbek",
        "italian": "Baal Netbek",
        "japanese": "Baal Netbek",
        "polish": "Baal Netbek",
        "russian": "Идол Нетбек",
        "schinese": "Baal Netbek",
        "spanish": "Baal Netbek"
    },
    "baalorun_old": {
        "brazilian": "Baal Orun",
        "english": "Baal Orun",
        "french": "Baal Orun",
        "german": "Baal Orun",
        "italian": "Baal Orun",
        "japanese": "Baal Orun",
        "polish": "Baal Orun",
        "russian": "Идол Орун",
        "schinese": "Baal Orun",
        "spanish": "Baal Orun"
    },
    "baalparvez_old": {
        "brazilian": "Baal Parvez",
        "english": "Baal Parvez",
        "french": "Baal Parvez",
        "german": "Baal Parvez",
        "italian": "Baal Parvez",
        "japanese": "Baal Parvez",
        "polish": "Baal Parvez",
        "russian": "Идол Парвез",
        "schinese": "Baal Parvez",
        "spanish": "Baal Parvez"
    },
    "baaltaran_old": {
        "brazilian": "Baal Taran",
        "english": "Baal Taran",
        "french": "Baal Taran",
        "german": "Baal Taran",
        "italian": "Baal Taran",
        "japanese": "Baal Taran",
        "polish": "Baal Taran",
        "russian": "Идол Таран",
        "schinese": "Baal Taran",
        "spanish": "Baal Taran"
    },
    "baaltondral_old": {
        "brazilian": "Baal Tondral",
        "english": "Baal Tondral",
        "french": "Baal Tondral",
        "german": "Baal Tondral",
        "italian": "Baal Tondral",
        "japanese": "Baal Tondral",
        "polish": "Baal Tondral",
        "russian": "Идол Тондрал",
        "schinese": "Baal Tondral",
        "spanish": "Baal Tondral"
    },
    "baaltyon_old": {
        "brazilian": "Baal Tyon",
        "english": "Baal Tyon",
        "french": "Baal Tyon",
        "german": "Baal Tyon",
        "italian": "Baal Tyon",
        "japanese": "Baal Tyon",
        "polish": "Baal Tyon",
        "russian": "Идол Тион",
        "schinese": "Baal Tyon",
        "spanish": "Baal Tyon"
    },
    "diego": {
        "brazilian": "Diego",
        "english": "Diego",
        "french": "Diego",
        "german": "Diego",
        "italian": "Diego",
        "japanese": "Diego",
        "polish": "Diego",
        "russian": "Диего",
        "schinese": "Diego",
        "spanish": "Diego"
    },
    "lester": {
        "brazilian": "Lester",
        "english": "Lester",
        "french": "Lester",
        "german": "Lester",
        "italian": "Lester",
        "japanese": "Lester",
        "polish": "Lester",
        "russian": "Лестер",
        "schinese": "Lester",
        "spanish": "Lester"
    },
    "lukor": {
        "brazilian": "Lukor",
        "english": "Lukor",
        "french": "Lukor",
        "german": "Lukor",
        "italian": "Lukor",
        "japanese": "Lukor",
        "polish": "Lukor",
        "russian": "Люкор",
        "schinese": "Lukor",
        "spanish": "Lukor"
    },
    "mud": {
        "brazilian": "Mud",
        "english": "Mud",
        "french": "Mud",
        "german": "Mud",
        "italian": "Mud",
        "japanese": "Mud",
        "polish": "Mud",
        "russian": "Мад",
        "schinese": "Mud",
        "spanish": "Mud"
    },
    "orc": {
        "brazilian": "Orc",
        "english": "Orc",
        "french": "Orc",
        "german": "Orc",
        "italian": "Orc",
        "japanese": "Orc",
        "polish": "Orc",
        "russian": "Орк",
        "schinese": "Orc",
        "spanish": "Orc"
    },
    "peasant": {
        "brazilian": "Peasant",
        "english": "Peasant",
        "french": "Peasant",
        "german": "Peasant",
        "italian": "Peasant",
        "japanese": "Peasant",
        "polish": "Peasant",
        "russian": "Крестьянин",
        "schinese": "Peasant",
        "spanish": "Peasant"
    },
    "templar": {
        "brazilian": "Templar",
        "english": "Templar",
        "french": "Templar",
        "german": "Templar",
        "italian": "Templar",
        "japanese": "Templar",
        "polish": "Templar",
        "russian": "Страж",
        "schinese": "Templar",
        "spanish": "Templar"
    },
    "novice": {
        "brazilian": "Novice",
        "english": "Novice",
        "french": "Novice",
        "german": "Novice",
        "italian": "Novice",
        "japanese": "Novice",
        "polish": "Novice",
        "russian": "Послушник",
        "schinese": "Novice",
        "spanish": "Novice"
    },
    "mercenary": {
        "brazilian": "Mercenary",
        "english": "Mercenary",
        "french": "Mercenary",
        "german": "Mercenary",
        "italian": "Mercenary",
        "japanese": "Mercenary",
        "polish": "Mercenary",
        "russian": "Наемник",
        "schinese": "Mercenary",
        "spanish": "Mercenary"
    },
    "bandit": {
        "brazilian": "Bandit",
        "english": "Bandit",
        "french": "Bandit",
        "german": "Bandit",
        "italian": "Bandit",
        "japanese": "Bandit",
        "polish": "Bandit",
        "russian": "Бандит",
        "schinese": "Bandit",
        "spanish": "Bandit"
    },
    "browniepoints": {
        "brazilian": "Trust Points",
        "english": "Trust Points",
        "french": "Trust Points",
        "german": "Trust Points",
        "italian": "Trust Points",
        "japanese": "Trust Points",
        "polish": "Trust Points",
        "russian": "Очки доверия",
        "schinese": "Trust Points",
        "spanish": "Trust Points"
    },
    "qd_questdealer": {
        "brazilian": "Quest Giver",
        "english": "Quest Giver",
        "french": "Quest Giver",
        "german": "Quest Giver",
        "italian": "Quest Giver",
        "japanese": "Quest Giver",
        "polish": "Quest Giver",
        "russian": "Квестодатель",
        "schinese": "Quest Giver",
        "spanish": "Quest Giver"
    },
    "unittest_unittest_unittest_2203": {
        "brazilian": "[Unit Test]",
        "english": "[Unit Test]",
        "french": "[Unit Test]",
        "german": "[Unit Test]",
        "italian": "[Unit Test]",
        "japanese": "[Unit Test]",
        "polish": "[Unit Test]",
        "russian": "[Технический тест]",
        "schinese": "[Unit Test]",
        "spanish": "[Unit Test]"
    },
    "orctemplewarriorm02": {
        "brazilian": "Orc Temple Warrior",
        "english": "Orc Temple Warrior",
        "french": "Orc Temple Warrior",
        "german": "Orc Temple Warrior",
        "italian": "Orc Temple Warrior",
        "japanese": "Orc Temple Warrior",
        "polish": "Orc Temple Warrior",
        "russian": "Воин храма орков",
        "schinese": "Orc Temple Warrior",
        "spanish": "Orc Temple Warrior"
    },
    "st_god_sleeper": {
        "brazilian": "The Sleeper",
        "english": "The Sleeper",
        "french": "The Sleeper",
        "german": "The Sleeper",
        "italian": "The Sleeper",
        "japanese": "The Sleeper",
        "polish": "The Sleeper",
        "russian": "Спящий (Божество)",
        "schinese": "The Sleeper",
        "spanish": "The Sleeper"
    },
    "madcorkalom": {
        "brazilian": "Mad Cor Kalom",
        "english": "Mad Cor Kalom",
        "french": "Mad Cor Kalom",
        "german": "Mad Cor Kalom",
        "italian": "Mad Cor Kalom",
        "japanese": "Mad Cor Kalom",
        "polish": "Mad Cor Kalom",
        "russian": "Безумный Кор Галом",
        "schinese": "Mad Cor Kalom",
        "spanish": "Mad Cor Kalom"
    },
    "xardas_404": {
        "brazilian": "Xardas",
        "english": "Xardas",
        "french": "Xardas",
        "german": "Xardas",
        "italian": "Xardas",
        "japanese": "Xardas",
        "polish": "Xardas",
        "russian": "Ксардас",
        "schinese": "Xardas",
        "spanish": "Xardas"
    },
    "xardasdemon": {
        "brazilian": "Xardas' Demon",
        "english": "Xardas' Demon",
        "french": "Xardas' Demon",
        "german": "Xardas' Demon",
        "italian": "Xardas' Demon",
        "japanese": "Xardas' Demon",
        "polish": "Xardas' Demon",
        "russian": "Демон Ксардаса",
        "schinese": "Xardas' Demon",
        "spanish": "Xardas' Demon"
    }
}

GOTHIC_ROLE_SHORTCUTS = {
    "grd": {
        "brazilian": "Guard",
        "english": "Guard",
        "french": "Guard",
        "german": "Guard",
        "italian": "Guard",
        "japanese": "Guard",
        "polish": "Guard",
        "russian": "Стражник",
        "schinese": "Guard",
        "spanish": "Guard"
    },
    "guard": {
        "brazilian": "Guard",
        "english": "Guard",
        "french": "Guard",
        "german": "Guard",
        "italian": "Guard",
        "japanese": "Guard",
        "polish": "Guard",
        "russian": "Стражник",
        "schinese": "Guard",
        "spanish": "Guard"
    },
    "sld": {
        "brazilian": "Mercenary",
        "english": "Mercenary",
        "french": "Mercenary",
        "german": "Mercenary",
        "italian": "Mercenary",
        "japanese": "Mercenary",
        "polish": "Mercenary",
        "russian": "Наемник",
        "schinese": "Mercenary",
        "spanish": "Mercenary"
    },
    "mercenary": {
        "brazilian": "Mercenary",
        "english": "Mercenary",
        "french": "Mercenary",
        "german": "Mercenary",
        "italian": "Mercenary",
        "japanese": "Mercenary",
        "polish": "Mercenary",
        "russian": "Наемник",
        "schinese": "Mercenary",
        "spanish": "Mercenary"
    },
    "org": {
        "brazilian": "Rogue",
        "english": "Rogue",
        "french": "Rogue",
        "german": "Rogue",
        "italian": "Rogue",
        "japanese": "Rogue",
        "polish": "Rogue",
        "russian": "Вор",
        "schinese": "Rogue",
        "spanish": "Rogue"
    },
    "rogue": {
        "brazilian": "Rogue",
        "english": "Rogue",
        "french": "Rogue",
        "german": "Rogue",
        "italian": "Rogue",
        "japanese": "Rogue",
        "polish": "Rogue",
        "russian": "Вор",
        "schinese": "Rogue",
        "spanish": "Rogue"
    },
    "bandit": {
        "brazilian": "Bandit",
        "english": "Bandit",
        "french": "Bandit",
        "german": "Bandit",
        "italian": "Bandit",
        "japanese": "Bandit",
        "polish": "Bandit",
        "russian": "Бандит",
        "schinese": "Bandit",
        "spanish": "Bandit"
    },
    "stt": {
        "brazilian": "Shadow",
        "english": "Shadow",
        "french": "Shadow",
        "german": "Shadow",
        "italian": "Shadow",
        "japanese": "Shadow",
        "polish": "Shadow",
        "russian": "Призрак",
        "schinese": "Shadow",
        "spanish": "Shadow"
    },
    "shadow": {
        "brazilian": "Shadow",
        "english": "Shadow",
        "french": "Shadow",
        "german": "Shadow",
        "italian": "Shadow",
        "japanese": "Shadow",
        "polish": "Shadow",
        "russian": "Призрак",
        "schinese": "Shadow",
        "spanish": "Shadow"
    },
    "vlk": {
        "brazilian": "Digger",
        "english": "Digger",
        "french": "Digger",
        "german": "Digger",
        "italian": "Digger",
        "japanese": "Digger",
        "polish": "Digger",
        "russian": "Рудокоп",
        "schinese": "Digger",
        "spanish": "Digger"
    },
    "digger": {
        "brazilian": "Digger",
        "english": "Digger",
        "french": "Digger",
        "german": "Digger",
        "italian": "Digger",
        "japanese": "Digger",
        "polish": "Digger",
        "russian": "Рудокоп",
        "schinese": "Digger",
        "spanish": "Digger"
    },
    "nov": {
        "brazilian": "Novice",
        "english": "Novice",
        "french": "Novice",
        "german": "Novice",
        "italian": "Novice",
        "japanese": "Novice",
        "polish": "Novice",
        "russian": "Послушник",
        "schinese": "Novice",
        "spanish": "Novice"
    },
    "novice": {
        "brazilian": "Novice",
        "english": "Novice",
        "french": "Novice",
        "german": "Novice",
        "italian": "Novice",
        "japanese": "Novice",
        "polish": "Novice",
        "russian": "Послушник",
        "schinese": "Novice",
        "spanish": "Novice"
    },
    "tpl": {
        "brazilian": "Templar",
        "english": "Templar",
        "french": "Templar",
        "german": "Templar",
        "italian": "Templar",
        "japanese": "Templar",
        "polish": "Templar",
        "russian": "Страж",
        "schinese": "Templar",
        "spanish": "Templar"
    },
    "templar": {
        "brazilian": "Templar",
        "english": "Templar",
        "french": "Templar",
        "german": "Templar",
        "italian": "Templar",
        "japanese": "Templar",
        "polish": "Templar",
        "russian": "Страж",
        "schinese": "Templar",
        "spanish": "Templar"
    },
    "kdw": {
        "brazilian": "Water Mage",
        "english": "Water Mage",
        "french": "Water Mage",
        "german": "Water Mage",
        "italian": "Water Mage",
        "japanese": "Water Mage",
        "polish": "Water Mage",
        "russian": "Маг Воды",
        "schinese": "Water Mage",
        "spanish": "Water Mage"
    },
    "kdf": {
        "brazilian": "Fire Mage",
        "english": "Fire Mage",
        "french": "Fire Mage",
        "german": "Fire Mage",
        "italian": "Fire Mage",
        "japanese": "Fire Mage",
        "polish": "Fire Mage",
        "russian": "Маг Огня",
        "schinese": "Fire Mage",
        "spanish": "Fire Mage"
    },
    "fm": {
        "brazilian": "Fire Mage",
        "english": "Fire Mage",
        "french": "Fire Mage",
        "german": "Fire Mage",
        "italian": "Fire Mage",
        "japanese": "Fire Mage",
        "polish": "Fire Mage",
        "russian": "Маг Огня",
        "schinese": "Fire Mage",
        "spanish": "Fire Mage"
    },
    "bau": {
        "brazilian": "Peasant",
        "english": "Peasant",
        "french": "Peasant",
        "german": "Peasant",
        "italian": "Peasant",
        "japanese": "Peasant",
        "polish": "Peasant",
        "russian": "Крестьянин",
        "schinese": "Peasant",
        "spanish": "Peasant"
    },
    "peasant": {
        "brazilian": "Peasant",
        "english": "Peasant",
        "french": "Peasant",
        "german": "Peasant",
        "italian": "Peasant",
        "japanese": "Peasant",
        "polish": "Peasant",
        "russian": "Крестьянин",
        "schinese": "Peasant",
        "spanish": "Peasant"
    },
    "sfb": {
        "brazilian": "Scraper",
        "english": "Scraper",
        "french": "Scraper",
        "german": "Scraper",
        "italian": "Scraper",
        "japanese": "Scraper",
        "polish": "Scraper",
        "russian": "Скребок",
        "schinese": "Scraper",
        "spanish": "Scraper"
    },
    "scraper": {
        "brazilian": "Scraper",
        "english": "Scraper",
        "french": "Scraper",
        "german": "Scraper",
        "italian": "Scraper",
        "japanese": "Scraper",
        "polish": "Scraper",
        "russian": "Скребок",
        "schinese": "Scraper",
        "spanish": "Scraper"
    }
}